# Generated by Django 6.0.5 on 2026-06-06 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('SHOW', 'Show'), ('FEIRA', 'Feira'), ('TEATRO', 'Teatro'), ('EXPOSICAO', 'Exposição'), ('RELIGIOSO', 'Religioso'), ('OUTRO', 'Outro')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
