# Generated by Django 6.0.5 on 2026-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('cultura', 'Cultura'), ('esporte', 'Esporte'), ('educacao', 'Educação'), ('tecnologia', 'Tecnologia'), ('musica', 'Música'), ('teatro', 'Teatro'), ('gastronomia', 'Gastronomia'), ('outros', 'Outros')], max_length=20),
        ),
    ]
